const dummySlides = [
  {
    id: 1,
    title: '드라마틱한 여정',
    description: '용기를 찾아 떠나는 판타지 모험이 시작됩니다.',
    color: '#1f2124',
    age: '15+',
    views: '1.2M',
    runtime: '132분',
    genre: '판타지',
  },
  {
    id: 2,
    title: '사랑의 온도',
    description: '서로 다른 세계, 하나의 감정.',
    color: '#27292c',
    age: '12+',
    views: '900K',
    runtime: '110분',
    genre: '로맨스',
  },
  {
    id: 3,
    title: '최후의 탈출',
    description: '모든 것을 걸고 탈출하라.',
    color: '#111315',
    age: '18+',
    views: '2M',
    runtime: '95분',
    genre: '스릴러',
  },
  {
    id: 4,
    title: '우주의 끝에서',
    description: '미지의 세계와 마주하다.',
    color: '#1a1c1f',
    age: '12+',
    views: '1.8M',
    runtime: '142분',
    genre: 'SF',
  },
  {
    id: 5,
    title: '미스터리한 소리',
    description: '당신이 믿는 소리는 진짜일까?',
    color: '#202224',
    age: '15+',
    views: '850K',
    runtime: '102분',
    genre: '미스터리',
  },
]

export default dummySlides
